name: PHP Composer & PHPCS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clear cache of Composer
      run: composer clear-cache

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install wpcs project
      run: composer create-project wp-coding-standards/wpcs --no-dev
      
    # Run PHPCS
    - name: PHP CodeSniffer
      uses: chekalsky/phpcs-action@v1
      with:
        enable_warnings: false
        installed_paths: '${{ github.workspace }}/vendor/phpcompatibility/php-compatibility,${{ github.workspace }}/vendor/phpcompatibility/php-compatibility-wp'
