name: PHP Composer & PHPCS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer update

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Run PHPCS
    - name: PHP CodeSniffer
      uses: chekalsky/phpcs-action@v1
