name: PHP Composer & PHPCS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clear cache of Composer
      run: composer clear-cache

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Echo current path
      run: echo $PWD
      
    # Run PHPCS
    - name: PHP CodeSniffer
      uses: chekalsky/phpcs-action@option-installed-paths
      with:
        enable_warnings: false
        installed_paths: /home/runner/work/adminimize/adminimize/wpcs
